### ISSUE TITLE
Design mock-up for login Screen

### ISSUE THREAD

**Issue by catalin-sc** [SpamExperts/mobile-app#4]
http://bit.ly/AppLoginScreen

**Comment by tonyandrewmeyer** [comment]
We should remove the hyphen from "log-in". It's the action, so it's "log in".

**Comment by ccatalinstoian** [comment]
While performing tests on the feature I noticed the following:
1. The logo from the top of the page does not contain the registered trademark sign;
2. The labels of the fields and the checksbox are not alligned on the left side as they are in the screenshot attached;
3. The checkbox need to be slightly bigger so the user can succesfully select it and when being unckecked it should not have borders as shown in the screenshot.
4. The text "Having trouble logging in" should have the same colour as the logo from the top;
5. The question mark help from Hostname should still be available because depending on the resolution of the phone the user cannot see the `Having trouble logging in` link.

**Comment by ccatalinstoian** [comment]
I performed tests and found small issues:
1) It can be noticed that by selecting the question mark for more information that the selector for writing in the hostname filed is present. Please view the attached file.
2) The question mark for `Having trouble logging in` link is missing.
3) Also as the screenshot from the description it seems to be some more space on the top of the page between "Hostname" and the top
![screenshot from 2017-02-02 16 09 38](https://cloud.githubusercontent.com/assets/15264948/22553557/d79d513e-e965-11e6-8b3a-65fe036a1d0b.png)
.

**Comment by ccatalinstoian** [comment]
I performed tests on the feature and the result is passed.
