### ISSUE TITLE
Unsuitable results on login (proxy server = test server address)

### ISSUE THREAD

**Issue by cristinav74** [SpamExperts/mobile-app#47]
### Version information
6156d19

### Steps to replicate
Use a test-server as proxy.
 1) valid username & password and any kind of input as hostname 
 2) valid hosname & password and invalid username
 3) valid hostname & username and invalid password

### Actual result
1) Successful login
2) 2 or 3 Error messages in cascade
3) 2 or 3 Error messages in cascade

### Expected result
1) Error message
2) One Error message
3) One Error message

### Other notes
Results obtained through manual testing

**Comment by nicolaeSE** [comment]
Everything works as expected here.
Whenever we work on testing or development we need to setup a server proxy to avoid CORS problems. 
In such cases setting up the hostname is actually useless since any request will actually be sent to the proxy server - it makes sense in such case for the hostname to be ignored so it will perform requests to the localhost - thus avoiding the CORS problem.

For the other two issues, I see correct messages. Indeed there was some temporary issue due to DB updates, but that was related to the mobile app endpoints.
